### ISSUE TITLE
Need to update rdma_setup.sh scripts to use NetworkManager for managing connections

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#104]
The files in /etc/sysconfig/network-scripts are no longer present or usable in Fedora Rawhide, need to update the rdma-setup code to manage the file using NetworkManager approved methods instead.

**Comment by JSpewock** [comment]
As a note, support for using ifcfg files in Fedora is no longer shipped with the distro after Fedora 36 and you have to install a plugin for the backwards compatibility, but this plugin will no longer be available starting in Fedora 41.

https://fedoraproject.org/wiki/Changes/MigrateIfcfgToKeyfile

**Comment by dledford** [comment]
Converging on a new ansible playbook setup and that will resolve this issue.
