### ISSUE TITLE
Replace upstream repo in beaker with a local repo so we can add restraint releases not pushed upstream

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#110]
The upstream beaker-project.org/yum/harness group of repos is out of date and doesn't support the latest releases.  Copy into a local repo and reconfigure the beaker or beaker snippets, whichever is needed, to point at the local repo instead of the upstream repo.

**Comment by JSpewock** [comment]
This is already done for us through the local directory created by beaker at `/var/www/beaker/harness/`. This directory is local on the beaker server and is served already so adding new restraint releases should be as easy as adding the packages we need to this directory and beaker will point to them by default.

**Comment by JSpewock** [comment]
Tested and working with the locally handled repo
