### ISSUE TITLE
RHEL 9 provisions but fails to start check-install task

### ISSUE THREAD

**Issue by JSpewock** [OpenFabrics/fsdp_docs#111]
With the new locally added harness, when hosts are provisioned with RHEL 9 the OS is installed on the host and the installation task completes but it then stops and fails to start running the "check-install" task.

**Comment by JSpewock** [comment]
Likely cause is beaker failing to install `restraint-rhts` because the RHEL9 harness repository we're using is a copy of CentOSStream9 which doesn't include the rhts (Red Hat Test System) version of restraint in it's packages, it only contains the restraint package

**Comment by JSpewock** [comment]
@dledford after trying to run a RHEL9 provision with `restraint` as the harness rather than `restraint-rhts` it still fails. This seems to be because the check install task requires the rhts version rather than base restraint as seen in [the harness.log of the failed job](https://beaker.ofa.iol.unh.edu/bkr/recipes/1231#task3104). 

Is there anyway we can get the packages for `restraint-rhts` built for RHEL9 so we can add them or, even better, find a way to poke the maintainer of the harness package repositories and see if we can get them to create directories for the latest distros and push them to https://beaker-project.org/yum/harness/ so we can get Fedora 36 harness packages up and running as well?

**Comment by JSpewock** [comment]
Spoke about during team meeting, planned to get the packages for all the Fedoras and RHEL 9 to add to our local repository for next meeting which should resolve this issue

**Comment by dledford** [comment]
I'll send a copy of the necessary restraint files to Jeremy in email

**Comment by dledford** [comment]
We need Fedora36/37 and RHEL9.  Will send all three in email.

**Comment by JSpewock** [comment]
Provisioning RHEL9 works with the new harness packages
