### ISSUE TITLE
Unable to login to beaker server

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#128]
Login attempts just sit and spin indefinitely.  I suspect something went wrong in binding the beaker instance to the new IPA server in the IPA server migration.

**Comment by dledford** [comment]
@JSpewock @lylavoie New issue blocking access to the cluster

**Comment by dledford** [comment]
Server eventually returns a 500 error page when attempting to login

**Comment by JSpewock** [comment]
Thank you for bringing this issue to our attention. Lincoln is out today, but I will sync with him about this on Monday morning. In the meantime however, I'll dig into the issue and try to diagnose it. This might cause some downtime over the weekend however.

**Comment by lylavoie** [comment]
Fixed, with updating routes to FreeIPA server.
