### ISSUE TITLE
Need to install Ethernet switch and cable up cards (once it arrives) then document that here

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#15]

**Comment by lylavoie** [comment]
Capturing the discussion for the FSDP meeting, we will start with running SONIC on the EdgeCore switch (WEDGE 100BF-32X).  We will need to ensure the NOS will allow configuration of the flow control and priority settings for the switch ports.

**Comment by dledford** [comment]
Test using a 100G-25G breakout on a port set to 40G-10G breakout mode to see if that works.  Once done, we'll place an order for the proper number and speed of breakout cables.

**Comment by shall1024** [comment]
Currently we need the following cables to complete this task: 

* 2 Intel 100G Cables
* 4 Broadcom 100G Cables
* 2 breakout cables (4 lanes, 25G each)

**Comment by dledford** [comment]
Is there a specific length you want for these?  I would suspect that 1m cables would work given how few machines there are in the rack so far.  If not 1m, then certain 2m is plenty long enough, yes?

----- Original Message -----
> Currently we need the following cables to complete this task:
> 
> * 2 Intel 100G Cables
> * 4 Broadcom 100G Cables
> * 2 breakout cables (4 lanes, 25G each)
> 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenFabrics/fsdp_docs/issues/15#issuecomment-780830457

-- 
Doug Ledford <dledford@redhat.com>
              GPG KeyID: 0E572FDD

**Comment by lylavoie** [comment]
Yes, 1m please

**Comment by dledford** [comment]
I've picked out the cables and sent the cart to Jim to have LF place the order on a OFA credit card.

**Comment by dledford** [comment]
The cables are just coming with a Cisco compatible ID.  They didn't have Broadcom or Intel in the list unless you ordered custom cables, which come from Asia and take much longer for shipping.

**Comment by lylavoie** [comment]
Cables have arrived, once installed, we'll update the switch documentation, and close this issue.

**Comment by shall1024** [comment]
Cables have been installed, and the documentation has been updated.
