### ISSUE TITLE
Need to install and cable up IB switch (once it arrives) and document that here

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#16]

**Comment by shall1024** [comment]
@dledford Currently we need the following cables to complete this task:

    2 Mellanox 100G IB Cables
    2 Broadcom 200G IB Cables

**Comment by dledford** [comment]
I'm confused.  Broadcom doesn't do IB, so 2 Broadcom 200G IB cables makes
no sense.  Do you mean 2 Broadcom 200G Eth cables?

And is this just to hook up second ports on dual port cards, or is this
needed to hook up the first ports on the cards?

**Comment by shall1024** [comment]
My apologies, I'm not sure why I typed Broadcom, it should be **Mellanox 200G IB cables**. I edited the comment above. 

We have two each of the following:
**Mellanox MCX653106A-HDAT 200G 2-port 
Mellanox MCX556A-ECAT 100G 2-port**

I connected **both ports** of one of each type of card, leaving one of each card not connected to the switch.

Please let me know if I should change it so all four cards have one port connected to the switch.

**Comment by shall1024** [comment]
**One port** of each type of card listed above is now connected to all four cards listed above.

Currently, our cable needs are as follows for the **Mellanox CX654106A 200G** cards:

```
2 Mellanox 200G IB Cables
```
