### ISSUE TITLE
Need to order breakout cables for Ethernet cards

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#17]

**Comment by dledford** [comment]
Will order after we know if we can just buy all 100G->25G cables or if we need to specify actual 40->10G breakout cables

**Comment by lylavoie** [comment]
Before ordering, we will test if the breakout 25G cables can be used in a fall back mode to 10G.

**Comment by lylavoie** [comment]
Current cable count looks to be the following, not counting Mellanox cards (not yet in the lab).
- 25G breakout cable - one needed
- 100G cable - 6 needed

The above assumes all ports on all cards are connected (i.e. 2-port card have both ports connected), if this is not required, only the additional 25G breakout cable is needed.

There will be a PR soon that captures the current Ethernet Fabric wiring, the commits are in Sarah's forked repo.

**Comment by dledford** [comment]
Breakout cables were ordered.  See comments in issue #15

**Comment by lylavoie** [comment]
Have have arrived, closing this issue.
