### ISSUE TITLE
Need to test manual provision of client machines

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#18]

**Comment by shall1024** [comment]
I logged into node-05 without trying to provision the machine again and it seems like Fedora 33 never installed; the last OS I installed onto the node is what's currently on the system. 

I suspect it's the same issue I've had with trying to reserve the system automatically where it "failed to find repo for harness" and aborts almost immediately after trying to reserve the system, without even beginning the install process.
