### ISSUE TITLE
Need to set proper permissions on node-* machines

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#21]
@lylavoie 

Currently, these machines can't be checked out.  Ideally, they should use the permissions from the default pool so you only have to manage one set of permissions, but all users will need reserve permissions to be able to check them out.

Recommended settings for everyone:

View
Loan To Self
Control Power
Reserve

If people abuse the Loan to Self, we might have to take that away.

**Comment by shall1024** [comment]
Everyone has the View, Loan To Self, Control Power, and Reserve permissions in the FSDP Cluster Default Pool now.

**Comment by dledford** [comment]
@shall1024 

This isn't quite fixed yet.  You might have put the right permissions on the pool, but the individual node machines are still all using custom access policies on a per node basis, and that policy doesn't allow reasonable permissions.  You'll need to bring up each individual node, and on the Access Policy tab of each node change the radio box from Use Custom Access Policy to Use policy from pool and select the pool that you configured the access policy on.

**Comment by shall1024** [comment]
Hi Doug,

This should be fixed now, for all ten nodes. I apologize for missing this
step. Please let me know if there are still issues with the access policies
of the nodes.

-Sarah

**Comment by dledford** [comment]
Well, I can access the nodes now.  But they are still using a custom policy per node, which means any changes you want to make in the future must be done on each and every node.  You probably want to set them to use the access policy from the pool, which is already a much more complete profile in that it has separate perms for fsdpchairs, admins, and everyone else.  Right now, they only have one policy level for everyone, but you don't see the restrictions because, as admin, you are also the owner, and the permissions don't apply to the owner.

**Comment by shall1024** [comment]
This should be resolved now; all ten nodes are assigned to use policy from pool.
