### ISSUE TITLE
Password expiration is on

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#22]
@lylavoie 

If you go into your User->Permissions area of the beaker interface, you have the option to set your own custom root password in beaker.  While the default beaker password rotates, it's nice when a user sets their own custom password that it stays as is indefinitely.  Right now, I set it today, and it's saying it expires in two days.

**Comment by shall1024** [comment]
I have changed the setting so that custom user passwords do not expire at all.
