### ISSUE TITLE
Unable to manually provision any OS other than Fedora 31

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#27]
The list of available OSes does not populate during manual provision.

To replicate, check a machine out for manual operation (use the Take button under the owner and how long the machine has been idle in the top row of widgets on the page), then go to the Provision tab, try to select the OS Family and there will only be Fedora31 present, none of the other families are in the list.  Checking the Excluded Families tab does not show the other families as being excluded, so they just aren't showing up for some other reason.

This was on node-01 and node-02.  I didn't verify the same issue happens on all other nodes.

**Comment by shall1024** [comment]
Imported the other families we currently have hosted at https://beaker.ofa.iol.unh.edu/distros/ (Except for Ubuntu as we need to resolve [#25](https://github.com/OpenFabrics/fsdp_docs/issues/25) first. 

Please let us know if there are other RHEL/Fedora OSes we should import.

**Comment by shall1024** [comment]
The OSes are in Beaker but there are various errors when trying to provision anything other than Fedora 31.

**Comment by dledford** [comment]
As per issue #18, this is mostly now working.

**Comment by dledford** [comment]
Closing because issue is handled.  There are distros without a working harness, but that's being tracked in another issue.
