### ISSUE TITLE
Need to create technology specific pools and assign machines to them

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#28]
One of the methods used to select machines for tests is to have the automated scripts select from various pools based upon their needs.  For instance, if you are wanting to run tests of OPA, then you would select from the opa pool of machines (we used rdma-opa inside Red Hat, but only because our beaker instance has lots of non-RDMA machines and we wanted to guarantee our pools were unique).  The suggested pools are:

opa
roce
iw or iwarp
ib

Then, in addition, we often need to specify specific brands in order to target specific drivers.  So, in addition to pools for the technology, there would be secondary pools for the driver in use.  Such as:

opa-hfi1
roce-mlx4
roce-mlx5
roce-mlx5-advanced (for the high end cards with things like Bluefield capability)
roce-intel
roce-qede
roce-bnxt
roce-bnxt-advanced (for things like Thor cards)
iw-chelsio
iw-intel
iw-qede
ib-mlx4
ib-mlx5
ib-mlx5-advanced

Depending on the hardware we actually get in, we might not need all these pools.  But this is how a test script can both a) guarantee homogeneous testing when desired and b) guarantee cross vendor compatibility when desired.

**Comment by shall1024** [comment]
The first list of suggested pools is complete to the best of our ability so far (ib pool has not been populated). Specific brands are still in process, they are somewhat populated but still need to confirm the technologies supported on some of the cards.

**Comment by lylavoie** [comment]
@shall1024  can you add a comment here of the list that are left "ToDo."

**Comment by shall1024** [comment]
Done: 
opa
opa-hfi1
roce
roce-intel
iw/iwarp
iw-chelsio
iw-intel

To Do:
roce-mlx4
roce-mlx5
roce-mlx5-advanced
roce-qede
roce-bnxt
roce-bnxt-advanced
ib-mlx4
ib-mlx5
ib-mlx5-advanced

**Comment by lylavoie** [comment]
Blocked by #86

**Comment by dledford** [comment]
I can't set the pools, permission problems.  Reassigning to @JSpewock

**Comment by JSpewock** [comment]
I filled out all of the pools except for the advanced ones. I wasn't 100% sure which cards applied to these categories, but I would assume the mlx5-advanced cards would be the Mellanox ConnectX-6 cards and the bnxt-advanced cards would be the Broadcom 57508 ones. @dledford can you confirm this?
