### ISSUE TITLE
Beaker snippets are not additive in certain situations

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#32]
I had hoped that we could do something like the following:

per_osmajor/packages/RHEL7:
%packages
rdma-core
libibverbs-utils
librdmacm-utils

per_machine/packages/node-01:
libhfi1
opa-ff

The idea was that we would have the core RDMA packages in the per_osmajor set, and then in the per_machine set just add the ones specific to the hardware installed in that machine.  It didn't work out that way.  It appears that the per_machine snippets override the per_osmajor snippets instead of adding to them.  I *think*, but I'm not sure, that we will need to do per machine package lists.  This needs additional testing to try and get the right packages installed as part of the base level install.

**Comment by dledford** [comment]
@shall1024 

New set of potential snippets has been pushed to fsdp_setup repo, please pull and then we can test.

In particular, any of the RHEL installs should:
1) Use the epel repo during install, and have it enabled after the install completes
2) Install the expanded package list, including a number of epel packages
3) git clone the fsdp_setup repo and attempt to run the setup
4) No longer have per-system package lists override/obliterate the per os major package lists

Time to test, please note here when you've pulled the snippets and I'm more than happy to start testing.

**Comment by shall1024** [comment]
@dledford , the snippets are pulled to beaker.ofa.iol.unh.edu and are ready to be tested. Please let us know if there's anything you would like us to test on our end.

**Comment by shall1024** [comment]
@dledford , the updates have been pulled to beaker.ofa.iol.unh.edu and are ready to be tested. Please let us know if there's anything you would like us to test on our end.

**Comment by shall1024** [comment]
We are looking into issues with "beaker-create-kickstart", as provisions seem to not be pulling in snippets correctly/using beaker-create-kickstart correctly.

**Comment by dledford** [comment]
Snippets aren't additive because they are prioritized.  The highest priority/most specific snippet is used in preference to more generally applied snippets.  Not a bug/issue.
