### ISSUE TITLE
Investigate GitHub Beaker repo

### ISSUE THREAD

**Issue by shall1024** [OpenFabrics/fsdp_docs#33]
See if the version of Beaker up on GitHub (or an earlier, tagged release) is newer than the "pre-packaged" version of Beaker we are using/if it is more appropriate for our use (more up-to-date harnesses, etc.)

**Comment by shall1024** [comment]
The latest version of Beaker on GitHub is 28.2; the version we have is 28.1. It's possible to upgrade Beaker on our systems without using the GitHub repo to this newest version. It seems like it is most up-to-date for us to use the "pre-packaged" version of Beaker + upgrades as they come available.

**Comment by lylavoie** [comment]
From the April 6 meeting, need to see if the Beaker GitHub repo provides the materials to create the RPM package for beaker, and if so, what it would take to make it easy to build / install that RPM package, so we can closely track the GitHub version.

**Comment by shall1024** [comment]
As far as I can tell, the Beaker GitHub repo does not provide the materials to create the RPM package for Beaker. It seems to only have some source code and documentation, no materials for installation at all/no RPM package files.

[The installation for the latest version of Beaker](https://beaker-project.org/docs/admin-guide/installation.html) is done via [yum repositories](https://beaker-project.org/download.html). On this yum repository page, you can also find tarballs containing the newest Beaker version, and older versions of Beaker. They have the same structure as the GitHub repository.

I'm unsure how to use these tarballs to build/install Beaker at this time, but this is something we could look into if it would be useful.

**Comment by lylavoie** [comment]
If it doesn't include the RPM Spec files to build an package to install, maybe this would be worth submitting to the project to make it easier for users to build / install.

**Comment by lylavoie** [comment]
Need to look into setting up a process to build the RPM package. We can likely grab the "starting" spec files from the RPM Source of the actual RHEL package, and then update that with new version information, etc.  We'll need to decide where we want to track those changes to the spec files, etc, i.e. an IOL repo or a repo on the OFA github, etc.  Just to streamline the process.  Right now, this issue is lower priority, compared to the builder-00 rebuild, etc.

**Comment by lylavoie** [comment]
When we look into making sure the SPEC file is fixed to not delete or replace the config files in /etc.

**Comment by dledford** [comment]
Until upstream adds support for more distros, which we'll want to pick up, we don't need to track the github repo our current install is working.
