### ISSUE TITLE
No slot available for MCX653106A-HDAT in builder-00

### ISSUE THREAD

**Issue by shall1024** [OpenFabrics/fsdp_docs#35]
MCX653106A-HDAT requires a PCIe x16 slot, but builder-00 currently does not have one available:

PCIe slot 1 (x16 full height): Intel Omni-Path 100HFA016LS adapter
PCIe slot 2 (x8 half height): None (but too small)
PCIe slot 3 (x16 half height): Unavailable due to installed RAID card

**Comment by lylavoie** [comment]
Remove the raid controller.  Move the two drives to SATA connection and then re-install / rebuild the system using a software raid.  Move the riser card from the test node we pulled the MCX card from.  Doug will order another riser card to replace the "stolen" one and we'll use that when the 3'rd MCX card arrives.  Need to confirm if we need any special cables for the SATA connections.

**Comment by lylavoie** [comment]
@dledford We need to order HPE Spare Part P07471-001, which is the 8SFF SATA cables for the front drive bays.  This is in addition to the riser card needed as well.

**Comment by dledford** [comment]
Part P07471-001 has been ordered direct from HPE, should be there Friday.  The riser card will take longer.  It wasn't available direct from HPE, so I'm having Jim order it from CDW, where the ship time is estimated at 6-10 days.

**Comment by lylavoie** [comment]
builder-00.ofa.iol.unh.edu has been reinstalled with software RAID, HPE raid card removed, and 16x slot 3 is available and populated with the MCX653106A-HDAT card (moved from node-08.iol.unh.edu), until the replacement arrives.

**Comment by dledford** [comment]
Riser and card reinstalled in node-08
