### ISSUE TITLE
Space for Mellanox Cx6541106A (200G) cards

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#37]
Each "card" requires two 16x PCI slots in the test host, there are no open 16x slots in the current hosts.

**Comment by shall1024** [comment]
We are going to move the card in PCI slot 1 of node-09 to PCI slot 1 of node-03, this will free up two 16x PCI slots in node-09 for one of the Mellanox Cx6541106A cards.

This only leaves one remaining 16x PCI slot open across all hosts, so we still cannot install one of the cards.

**Comment by dledford** [comment]
Bifurcated PCI card installed in node-09, second card put away as spare for when we have more client machines
