### ISSUE TITLE
Enable httpd and user home directory support on builder-00

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#39]
This is so users can build stuff in their home directory and easily access if on the node-* machines

**Comment by lylavoie** [comment]
This is done, httpd home directories work.   Currently users have to create the public_html directory.  Selinux will set the right file context on the directory when created.  I did run into a very strange issue, that I have not been able to solve. If I add public_html to the /etc/skel, it will cause the mkhomedir oddjob to fail.  It's blocked by something selinux related, but I have not been able to track it down. I don't think that is blocking to close this issue.
