### ISSUE TITLE
Beaker log storage

### ISSUE THREAD

**Issue by shall1024** [OpenFabrics/fsdp_docs#40]
As far as we can tell, the only way to change the location Beaker stores logs by default is by editing **/lib/python2.7/site-packages/bkr/labcontroller/default.conf** . We don't want to do this as the file is overwritten every time we upgrade Beaker.

Beaker documentation seems to suggest [we create a log archive server](https://beaker-project.org/docs/architecture-guide/log-storage.html), so this is likely what we will do.

We want to move logs from their default storage locations to **/mnt/data/beaker_logs**.

**Comment by lylavoie** [comment]
@JSpewock to run a hardware scan on node-04 to confirm the logs are working (take back machine from Doug)

**Comment by lylavoie** [comment]
@JSpewock finished this setup.  Actually accomplished via a bind mount, the beaker transfer daemon didn't work.
