### ISSUE TITLE
Unable to manually provision a machine without first loaning it to myself

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#44]
At some point in the past, I used to be able to bring up a machine's page, and in the little area that it shows the current machines status, if it was idle, I was allowed to Borrow the machine or Take the machine, either one.  Now, the Take button is missing and only the Borrow button is present.  If I Borrow the machine, then I get a Take and Return Loan buttons.  Once I Take the machine, then I am able to manually provision the machine.

**Comment by dledford** [comment]
@shall1024 Here's the new issue for you as per the call today

**Comment by shall1024** [comment]
Wasn't able to find a fix from looking at documentation and trying new access policies, created an issue for Beaker upstream [here](https://github.com/beaker-project/beaker/issues/133)

**Comment by dledford** [comment]
If you use the reserve workflow, this works.
