### ISSUE TITLE
Permissions on the FSDP pool need a minor update

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#45]
While we want the FSDP chairs to be able to loan to anyone, Everyone should probably not have that privilege.

Also, FSDP chairs should have view permission on the machine.  Right now they can view anyone because everyone has it, it's just odd that they don't.

**Comment by dledford** [comment]
In addition, Edit System Details would a nice to have for the FSDP chairs.  That allows us to make updates to the system, such as having the ability to re-run the hardware scans when the hardware has been updated, and to edit the Model field to allow people to see the types of cards in the systems without having to bring up separate documentation like we do inside Red Hat, as so:



rdma-dev-00.lab.bos.redhat.com | i386, x86_64 | Dell | PowerEdge R320 - mlx4 MT27500 CX-3 ib0/ib1 56 | gtiwari | Automated | Machine | gtiwari
-- | -- | -- | -- | -- | -- | -- | --
rdma-dev-01.lab.bos.redhat.com | i386, x86_64 | Dell | PowerEdge R320 - mlx4 MT27500 CX-3 ib0/ib1 56 | &nbsp; | Automated | Machine | &nbsp;
rdma-dev-02.lab.bos.redhat.com | i386, x86_64 | Dell | PowerEdge R320 - qede 45000 iw 25 | &nbsp; | Automated | Machine | &nbsp;
rdma-dev-03.lab.bos.redhat.com | i386, x86_64 | Dell | PowerEdge R320 - qede 45000 iw 25 | &nbsp; | Automated | Machine | &nbsp;
rdma-dev-06.lab.bos.redhat.com | x86_64 | Dell | PowerEdge R320 - qib ib0/ib1 40 | &nbsp; | Automated | Machine | &nbsp;
rdma-dev-07.lab.bos.redhat.com | x86_64 | Dell | PowerEdge R320 - qib ib0/ib1 40 | &nbsp; | Automated | Machine | &nbsp;
rdma-dev-10.lab.bos.redhat.com | i386, x86_64 | HP | ProLiant DL320e Gen8 - mlx4 MT27500 CX-3 ib0/ib1 56 | &nbsp; | Broken | Machine | &nbsp;

**Comment by dledford** [comment]
@lylavoie I opened this issue, but you'll need to consider internally if you want to give the chairs edit details permission.  I don't  *think* we can do much, if any, damage with it, but I haven't checked either.

**Comment by shall1024** [comment]
FSDP chairs now have "View" and "Edit System Details" permissions in the FSDP Cluster Default Pool. 

Everyone has had the "Loan to Anyone" permission removed in the FSDP Cluster Default Pool.
