### ISSUE TITLE
Reserve Workflow not working

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#46]
It's possible to use the command line to submit a reserve job, but you are supposed to also be able to use the GUI to do so.  After I Borrow a machine, then Take the machine, then go to Provision, there is a link present that says if I want to, I can use the Reserve Workflow to reserve the machine.  When I try to do that, it takes me to the Reserve Workflow page, I select a distro, it already has the specific machine I got to this page from selected under the Specific System radio button, then I modify the time to be how long I want to do the reservation, but something in the Whiteboard field, then try to click the Submit Job button and it just never does anything.  I get the impression there's some field they want filled out, but there's no indication of what field that might be or how to rectify the situation.

**Comment by dledford** [comment]
@shall1024 This issue is related, but not necessarily the same, so I split it from the other one.

**Comment by shall1024** [comment]
Did you click on the single option listed in the "Distro Tree" box?

![image](https://user-images.githubusercontent.com/71143113/121731644-39aaef00-cabf-11eb-864f-f2472faf1124.png)

"Submit Job" will not do anything until this is selected. I agree it is unclear that this is a required option.

**Comment by dledford** [comment]
User error on my part, closing.
