### ISSUE TITLE
Need to reinstall the proper opafm config so the opa fabric will come up

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#55]
@shall1024 @lylavoie 

The config changes we made to the default opafm config file were lost during the builder rebuild.  We need to put them back in place.  Currently, the opa-fm package isn't installed on builder or I'd try to provide a patch.  But without the default file to patch against ;-)

1) Need to put the GID for the interface that's plugged into the switch in the file
2) Need to create an additional fabric using P_Key 20 so that we have multiple P_Keys on the fabric

**Comment by shall1024** [comment]
@dledford, opa-fm has ben reinstalled onto builder-00 with the old version of `opafm.xml`. 

I can't remember off the top off my head if steps 1 and 2 have been completed as indicated above, this is what I will check next.

**Comment by lylavoie** [comment]
This has been completed.
