### ISSUE TITLE
Need to iLO and BIOS settings updates across most of the cluster plus two hardware changes unrelated to the possible upcoming card shuffle.

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#71]
@lylavoie @JSpewock

A few settings need to be changed in the iLO interfaces.  I've tried setting them, but I'm only allowed to set them on some machines (due to a security oversight on those machines) and not allowed to set them on the machines properly configured.  I have been able to set these options on node-01, node-02, node-07, and node-08.  I couldn't set them on node-03 and node-04.  I didn't try on the others.

The things needing done are:

1) Make sure all machines iLO hostnames are "node-??-ipmi".  Whenever the iLO hostname does not resolve to a valid DNS hostname when postpended with the domain provided by dhcp, iLO automatically makes attempts to access the host redirect to an IP address instead of a hostname.  This presents problems with password managers.

2) On the nodes where I was able to set things, I did so by going into the BIOS screen by using the remote HTML5 console and hitting F9 for system utilities.  Then I was able to configure the iLO settings in the BIOS settings area and bypass the security checks that iLO itself applies.  On nodes 03 and 04, this didn't work because the BIOS was not allowed to configure iLO settings.  I imagine this needs set somewhere in iLO for all of the nodes.

3) And, in fact, we should probably password protect using the F9 System Utilities at the system startup across all nodes

4) Although the reason I was going in there in the first place was to put the Broadcom cards into RDMA mode instead of plain NIC mode, so a check of NIC settings when installing cards is probably something that should be on the checklist.

5) Node-05 still has it's HP Array controller installed and produced BIOS warnings on boot about not being able to talk to the battery backup for the HP Array controller.  It might or might not have the third PCI riser installed, but even if it does, I'm pretty sure the system won't recognize any card in the 3rd PCI slot until the HP Smart Array controller is removed.

6) Node-10 has a socket direct ConnectX6 card installed, which means it should be plugged into two PCI slots and the backplane in the second PCI slot connected to the card via ribbon cables.  The system is only showing one of the PCI slots in use by the ConnectX6 card.  The other part of the card is likely not seated well or the ribbon cables aren't seated well or something at the BIOS level is keeping the second slot card from being recognized.

**Comment by lylavoie** [comment]
Item 1 - iLO hostnames are fully set in the 10 nodes.

Items 2 / 3 - I'm not sure how to block the F9 tools in HPE.  I've selected an options that should require login for the RBSU tools, but it seems to have no effect when working in the virtual console.

Item 4 - Do we know which systems need this configuration, or do we need to check each system in BIOS (slower option)?

Item 5 - As far as I can tell this is resolved, there are definitely no raid cards in any of the 10 nodes, as the PCI3 riser won't fit if there were.  The BIOS does list it in system config, but I'm not sure how to make that go away, The lspci from within Linux does list a raid bus controller but I have no idea where that is coming from in terms of hardware.  It does not show up on other nodes.

Item 6 - node-09 and node-10 have the two deirect ConnectX6 cards and are listing the two PCI slots as in-use, so this should be all set now.
