### ISSUE TITLE
Pull extra cables and reuse where possible

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#76]
@lylavoie 
The extra cables installed right now are:

Switch Port | Sub Port | Connected To
-----|-----|-----
2 | N/A | node-01 Intel E810-CQDA2 100G 2-port RoCE Port 2
5 | N/A | node-02 Intel E810-CQDA2 100G 2-port RoCE Port 2
17 | N/A | node-07 Broadcom 57508 200G 1-port RoCE Port 2
19 | N/A | node-08 Broadcom 57508 200G 1-port RoCE Port 2

If any of those are 100gig FS cables, we should be able to use them to connect the CX556A cards in node-03 and node-04, port 1 of each to the IB switch and have them come up.

**Comment by lylavoie** [comment]
Will check this on Monday, October 18, I'm remote this week week.

Also need to check node-09 / node-10 QLogic FastLinQ QL41000 50G, which likely does not have the right break out cables conneted.
