### ISSUE TITLE
Beaker snippets not updating

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#88]
@JSpewock 
The beaker snippets are not getting updated from the fsdp_beaker_snippets repo.  I think when Sarah set it up, she had the cron job pulling to a local git repo, but then there was a manual copy step to put them in the actual directory beaker looks in or something like that.  Not sure, all I know is the changes I've made aren't showing up in the installs.

**Comment by JSpewock** [comment]
That's strange, all I changed about the cron job was the timer on it so the actual commands it executes shouldn't have changed. I'll look into it

**Comment by JSpewock** [comment]
@dledford This issue is resolved, it ended up being the directory `/etc/fsdp_beaker_snippets` which is the local git repository that pulls down the changes from the remote repo had the "rhel8_fixes" branch checked out so that's where it was pulling from instead of main.

**Comment by dledford** [comment]
@JSpewock You might need to see if there are any fixes on the rhel8_fixes branch that aren't in main.  If there are, we'll need to get them pulled into main.

**Comment by JSpewock** [comment]
rhel8_fixes looks like a dead branch essentially. It's 0 commits ahead of main and 5 behind so it's probably fine to even scrap it at this point
