### ISSUE TITLE
FSDP Setup not being run after successful beaker install

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#95]
FSDP setup doesn't look to be run during the kick start install.  The following (from the kick-start file created by Beaker) should be running the setup scripts.

```
# global system_post snippet
cd /root
git clone git://github.com/OpenFabrics/fsdp_setup
pushd fsdp_setup
./rdma-setup.sh
popd
```

**Comment by dledford** [comment]
This should be fixed.
