### ISSUE TITLE
Add Fedora Rawhide to the list of distros in Beaker

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#98]

**Comment by lylavoie** [comment]
For the workshop (i.e. in April), we can just do a snapshot (i.e. download the latest available ISO and import that). Longer in the future, we will figure out a way to setup a sync on the real repo (i.e. we host an internal mirror).

**Comment by lylavoie** [comment]
Also setup the OS major snippets, copying package list from Fedora 35.

**Comment by JSpewock** [comment]
I added a Fedora Rawhide snapshot from April 16th which provisions and works fine for now. Had to add a separate system_post snippet that allows for root ssh login on hosts that provision Fedora Rawhide.
